Sprint1
Darantars/mir-krasoty-site pull request #1
Opened 2022-10-04 18:24 UTC by Darantars

Сдаю задание 1ого спринта. Не получилось сделать блок с видео в секции "о салоне", не работающий стиль отмечен комментарием. Также есть 2 помеченных костыля, буду рад получить совет как сделать лучше.  Сожалею о задержке, но как я понял из вебинара, проверка в том спринте еще возможна. Задержался из-за новичкового подхода а-ля позиционировать отдельно каждую линия векторного рисунка(исправлено).

2022-10-07 01:48 UTC, brochmi commented on index.html
> +        <link rel="stylesheet" href="styles.css">
Свои стили нужно подключать ниже всех остальных. Мы можем захотеть переопределить внешние стили в своих.

2022-10-07 04:44 UTC, brochmi reviewed
`Требует доработки`
Привет! В общем сделано нормально, но есть места которые требуют доработок. Обрати внимание на форматирование документа. В некоторых местах inline стили паразитируют внешние стили.

2022-10-07 04:44 UTC, brochmi commented on styles.css
> +    padding-top: 14px;      /*выравнивал номер - высота шрифта - костыль*/
padding-top здесь вполне уместен. Но если нужно выравнивать его относительно всего блока .header-top, то нужно указать ему фиксированную высоту и настраивать вырывания для всех флекс элементов централизованно.

2022-10-07 04:44 UTC, brochmi commented on styles.css
> +    float: right;
Для общего блока секции сделать flex контейнер.

2022-10-07 04:44 UTC, brochmi commented on index.html
> +                            <img src="icons/we.png" alt="" id = "weVideo" height="296" style = "margin: 0px"  >
Inline стили переопределяют отступы  в #weVideo

2022-10-07 04:44 UTC, brochmi commented on styles.css
> +#weVideo::after{               /* Почему-то не работает */
Почитать об [этом](https://developer.mozilla.org/ru/docs/Web/CSS/::after) (см.примечание) - поправить

2022-10-08 06:45 UTC, brochmi requested changes
`Требует доработки`
Привет! В общем сделано нормально, но есть места которые требуют доработок. Обрати внимание на форматирование документа. В некоторых местах inline стили паразитируют внешние стили.

2022-10-09 15:55 UTC, Darantars commented
Исправил указанные проблемы, как я могу обновить пулл-реквест?

2022-10-10 03:58 UTC, brochmi approved these changes

2022-10-10 03:59 UTC, brochmi commented
> Исправил указанные проблемы, как я могу обновить пулл-реквест?

Увидел исправления. Апрувнул ПР

2022-10-10 10:22 UTC, merged